# Site
name: 'enoviti'
description: 'Enoviti is my space to share my professional experience with peers'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'enoviti'
email: 'apurohit@enoviti.com'
mailchimp-list: 'https://enoviti.us10.list-manage.com/subscribe/post?u=f615c5e142cb8aa79d93f0c0c&amp;id=8d72dabab6'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    anshuman:
      name:           Anshuman
      site:           https://www.enoviti.com
      avatar:         assets/images/avatar.GIF
      bio:            "Hi, I am Anshuman, the author of this Blog. I hope you like it!"
      email:          apurohit@enoviti.com
      twitter:        https://twitter.com/enoviti

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: anshuman
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]